swagger: '2.0'
info:
  description: Login API
  title: Login API
  version: 1.0.0
  contact:
    email: avikganguly010@gmail.com
tags:
  - name: developers
    description: Operations available to regular developers
paths:
  /login:
    post:
      tags:
        - developers
      summary: Logs a user in using Firebase token
      description: Logs a user in using Firebase token
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: firebaseUserId
          description: Firebase profile to add
          schema:
            type: object
            required:
              - firebaseUserId
            properties:
              firebaseUserId:
                type: string
                example: abcd123
      responses:
        '200':
          description: Session created
          schema:
            type: object
            properties:
              resourceId:
                type: integer
                description: The user ID.
        '400':
          description: 'invalid input, object invalid'
          

host: 'jammate.in'
basePath: /beatnik-core/
schemes:
  - http
  
  

